apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven
  labels:
    app: java-maven
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: java-maven
  template:
    metadata:
      labels:
        app: java-maven
    spec:
      imagePullSecrets:
      - name: my-docker-registry
      containers:
      - name: java-maven
        image: abanobmorkos10/java-maven:${IMAGE_VERSION} 
        imagePullPolicy: Always  
        ports:
        - containerPort: 8080