apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven
  labels:
    app: java-maven
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: java-maven
  template:
    metadata:
      labels:
        app: java-maven
    spec:
      imagePullSecrets:
      - name: aws-registry
      containers:
      - name: java-maven
        image: ${REPO_NAME}:${IMAGE_VERSION} 
        imagePullPolicy: Always  
        ports:
        - containerPort: 8080